; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp-wrover-kit]
platform = espressif32
board = esp-wrover-kit
framework = arduino
lib_deps =
   ; ansi escape sequence library
   robtillaart/ANSI@^0.3.2
	seeed-studio/Grove - LCD RGB Backlight @ 1.0.2
monitor_filters = direct
monitor_speed = 115200
;upload_protocol = esp-prog
;debug_init_break = tbreak setup 
;monitor_port = /dev/cu.usbserial-120
